# Generated by Django 4.2.16 on 2024-12-09 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
