# Generated by Django 4.2.16 on 2024-12-21 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_disease_habit_alter_assistant_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='body_temp',
            new_name='body_temperature',
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
    ]
