# Generated by Django 4.2.16 on 2024-12-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_doctor_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_treatment', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True)),
                ('treatment_location', models.CharField(blank=True, choices=[('VILLAGE_RMP', 'Village RMP'), ('TOWN_RMP', 'Town RMP'), ('CITY_SPECIALIST', 'City Specialist')], max_length=50, null=True)),
                ('treatment_type', models.CharField(blank=True, choices=[('ORAL_MEDICINES', 'Only Oral Medicines'), ('IV_IM_DRIP', 'Only IV/IM/Drip'), ('BOTH_ORAL_IV_IM_DRIP', 'Both Oral & IV/IM/Drip')], max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor',
        ),
        migrations.CreateModel(
            name='CaseFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('document_section', models.CharField(blank=True, choices=[('MEDICINE_PHOTO', 'Medicine Photo'), ('LAB_REPORT', 'Lab Report'), ('PHOTO', 'Photo')], max_length=60, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseChiefComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=20, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, choices=[('DAY', 'Day'), ('WEEK', 'Week')], max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
