# Generated by Django 4.2.16 on 2024-12-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_case_remove_patient_assigned_doctor_casefinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='patients', to='app.doctor'),
        ),
    ]
