# Generated by Django 4.2.16 on 2024-12-22 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_patient_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casechiefcomplaint',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chief_complaints', to='app.case'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.case'),
        ),
        migrations.AlterField(
            model_name='casefinding',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='app.case'),
        ),
    ]
