# Generated by Django 4.2.16 on 2024-12-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_speciality_doctor_especiality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='speciality',
        ),
    ]
