# Generated by Django 4.2.16 on 2024-12-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_doctor_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='especiality',
            new_name='speciality',
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
