# Generated by Django 4.2.16 on 2024-12-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_especiality_doctor_speciality_doctor_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_follow_up',
        ),
        migrations.AddField(
            model_name='case',
            name='follow_up_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
