# Generated by Django 4.2.16 on 2025-01-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_case_is_follow_up_case_follow_up_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='uploaded_file_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
