# Generated by Django 4.2.16 on 2025-01-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_casedocument_uploaded_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='body_temperature',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='note_on_vitals',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='oxygen',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight',
        ),
        migrations.AddField(
            model_name='case',
            name='blood_sugar_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='body_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='high_blood_pressure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='low_blood_pressure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='note_on_vitals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='oxygen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='pulse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
