# Generated by Django 4.2.16 on 2025-01-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_patient_blood_pressure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='high_blood_pressure',
            new_name='blood_pressure_high',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='low_blood_pressure',
            new_name='blood_pressure_low',
        ),
    ]
