# Generated by Django 4.2.16 on 2025-01-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_high_blood_pressure_case_blood_pressure_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casechiefcomplaint',
            name='severity',
        ),
        migrations.AddField(
            model_name='case',
            name='complaint_severity',
            field=models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casechiefcomplaint',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('DAY', 'Day')], max_length=5, null=True),
        ),
    ]
