# Generated by Django 4.2.16 on 2025-01-16 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_casechiefcomplaint_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefinding',
            name='severity',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('HIGH', 'High')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='FindingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('uploaded_file_name', models.CharField(blank=True, max_length=512, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_images', to='app.casefinding')),
            ],
        ),
    ]
