# Generated by Django 4.2.16 on 2025-02-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_medicinedoseduration_medicinedosequantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='app.case')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicinedoseduration')),
                ('dose_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicinedosequantity')),
                ('dose_regimens', models.ManyToManyField(related_name='medicines', to='app.medicinedoseregimen')),
                ('dose_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicinedosetype')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicinename')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='app.prescription')),
            ],
        ),
    ]
