# Generated by Django 4.2.16 on 2025-02-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_prescription_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='notes',
            new_name='note',
        ),
        migrations.AddField(
            model_name='prescription',
            name='referred_doctors',
            field=models.ManyToManyField(blank=True, related_name='prescriptions', to='app.doctor'),
        ),
        migrations.CreateModel(
            name='DietAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_advices', to='app.prescription')),
            ],
        ),
    ]
