# Generated by Django 4.2.16 on 2025-02-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_diagnosis_investigation_investigationlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diagnosis')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_items', to='app.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investigation')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_items', to='app.prescription')),
            ],
        ),
        migrations.RemoveField(
            model_name='investigationlist',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='investigationlist',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='DiagnosisList',
        ),
        migrations.DeleteModel(
            name='InvestigationList',
        ),
    ]
