# Generated by Django 4.2.16 on 2025-03-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_diagnosisitem_investigationitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_follow_up_created',
            field=models.BooleanField(default=False),
        ),
    ]
